module.exports = {
  login: require('./users/login'),
  signup: require('./users/signup'),
  auth: require('./users/auth'),
  userInfo: require('./myInfos/userInfo'),
  logout: require('./users/logout'),
  modify: require('./myInfos/modify'),
  signout: require('./users/signout'),
  activity: require('./myInfos/activity'),
  episodeInfos: require('./search/episodeInfos'),
  comments: require('./search/comments'),
  add: require('./comments/add'),
  delete: require('./comments/delete'),
  like: require('./comments/like'),
};
