export const colors = {
  primary: '#FF826C',
  primaryL: '#FCDDD7',
  primaryD: '#E65C44',
  secondary: '#53D2DC',
  secondaryL: '#CCF3F6',
  secondaryD: '#14B4C0',
  grey: 'grey',
  greyL: '#EEEEEE',
  greyD: 'darkgrey',
  white: 'white',
  black: 'black',
  warning: '#CB4335',
  warningL: '#FADBD8',
};
